### ISSUE TITLE
Serialized data

### ISSUE THREAD

**Issue by Eriner** [Eriner/RCLootCouncil#13] opened 2015-01-14 02:16 UTC
council members are not revieving serialized data, something must be broken with the cross-realm patch.

**Comment by Eriner** [comment] 2015-01-14 03:18
players can roll on items, council doesn't get voting started. Error exists when ML has 1.6.7 and council has 1.6.5. functions as expected when ML has 1.6.5, council has 1.6.7. Error must exist in ML storage of council names.

**Comment by evil-morfar** [comment] 2015-01-14 10:55
Could be due to `UnitInRaid(v)` in line 1092 isn't accepting playerName-realmName, which means players are newer really counted as being in the council, thus never getting the voting shown.
`UnitInRaid(Ambiguate(v, "short"))` should solve it if that's the case. Can't test it myself.

**Comment by evil-morfar** [comment] 2015-01-14 11:03
In case the above doesn't work (and `UnitInRaid()` is the cause of the issue), this alternative should:
```lua
for i = 1, GetNumGroupMembers() do
    for _, v in ipairs(db.council) do
        if self:UnitIsUnit(v, select(1, GetRaidRosterInfo(i))) then
            tinsert(currentCouncil, v)
        end
    end
end
```

**Comment by evil-morfar** [comment] 2015-01-14 11:06
I just figured that since `UnitIsUnit` doesn't work with playerName-realmName it must be because it isn't a valid [`unitid` ] (http://www.wowwiki.com/UnitId). In that case my first suggestion should work, and we should check everything and make sure we don't use it as a `unitid` anywhere but `self:UnitIsUnit()` which strips the realmName.

**Comment by evil-morfar** [comment] 2015-01-14 12:59
Wow didn't know GitHub was smart enough to check for references :D

**Comment by Eriner** [comment] 2015-01-14 20:30
I know this is a miscelaneous request, but can you set autoclrf to true in your git config? https://help.github.com/articles/dealing-with-line-endings/

Can be set with git config --global core.autocrlf true

Otherwise I get "^M" at every line break, and causes me to remove them an commit 2k plus lines of code. Thanks :)

**Comment by Eriner** [comment] 2015-01-14 21:08
I also just gave you full modify access to this repository, which should help move things along and prevent duplicate work :)

**Comment by evil-morfar** [comment] 2015-01-15 00:10
My IDE did complain about line endings, but didn't know what caused it - its changed now.

I was wondering about my latest commits, because I merged the masters, and then worked with my master to create the new branches. Perhaps I just screwed up along the way...

**Comment by Eriner** [comment] 2015-01-15 08:28
well, just pull this master, and then merge/commit your changes. :)

**Comment by evil-morfar** [comment] 2015-01-17 11:40
Created branches for the commits on your repo - everything should be right this time.
I wanted to create a beta release of the combined changes. I tried to push them to my own master, but it couldn't auto merge, which I couldn't solve.

**Comment by evil-morfar** [comment] 2015-01-17 20:20
Curse ticket reminded me I forgot to mention all the recent changes isn't backwards compatible (from 1.6.6 beta). Release version should be 1.7.0.

**Comment by evil-morfar** [comment] 2015-01-18 23:04
I officially suck at merging branches....
Anyway, made 1.7-alpha, a merge of my recent changes, and pushed it to curse. Hopefully it should work and release 1.7.0 right around the corner.

**Closed** 2015-01-25 20:12 UTC
